### ISSUE TITLE
Issues running the script

### ISSUE THREAD

**Issue by X1nto** [abraha2d/Boot-Animation-Factory#1]
Hi, i'm trying to use the script, however i get the following error:

`xinto@BookSploit:~/Boot-Animation-Factory$` ./createBootAnimation.py /home/xinto/Desktop/vanced_9_1.gif

Info: 800x800 @ 33fps (0 frames)

Extrating frames from video...
/ |#                                               | 0 Elapsed Time: 0:00:00Traceback (most recent call last):
  File "./createBootAnimation.py", line 90, in <module>
    for packet in bar(container.demux()):
  File "/home/xinto/.local/lib/python3.7/site-packages/progressbar/bar.py", line 531, in __next__
    self.update(self.value + 1)
  File "/home/xinto/.local/lib/python3.7/site-packages/progressbar/bar.py", line 641, in update
    % (value, self.min_value, self.max_value))
ValueError: Value 1 is out of range, should be between 0 and 0`

can you tell me what am i doing wrong? thanks

**Comment by abraha2d** [comment]
Hi, the script was designed to convert video files like MP4, not GIFs.
However, it looks like it shouldn't be too hard to add support for GIFs. I'll see if I can do it some time.

**Comment by abraha2d** [comment]
https://kite.com/python/examples/4892/pil-extract-frames-from-an-animated-gif
Would need to detect when a GIF is used as input, and use something like the above instead of the `av` module around lines 68 and 90-93.
If you're up to the task, a PR would be much appreciated. Not sure if/when I'll get time to do it.

**Comment by X1nto** [comment]
Thanks mate, I'll convert this .gif to .mp4 and see if it will work

**Comment by X1nto** [comment]
> https://kite.com/python/examples/4892/pil-extract-frames-from-an-animated-gif
> Would need to detect when a GIF is used as input, and use something like the above instead of the `av` module around lines 68 and 90-93.
> If you're up to the task, a PR would be much appreciated. Not sure if/when I'll get time to do it.

I'll turn on my PC and see what can I do

**Comment by X1nto** [comment]
I've installed Image module via pip3, can I help you with something?

**Comment by X1nto** [comment]
Hi again, sorry for not responding for 4 months. So I've succesfully implemented gif file support with if/elif statements, (Yeah, i'm a noob xD). One thing i couldn't figure out is writing to desc.txt because PIL doesn't support height and width separately (I tried using .split() but no success) and doesn't support fps count too. would you mind checking the code (If you have free time) to see what's the problem? I couldn't find neither documentation or examples of using PIl. Everything is on my fork of this project.

**Comment by abraha2d** [comment]
I'll see if I can look into what you've got, thanks for giving it a shot.
